---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/glance-install.html
- name: configure prerequisites
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  environment: config.environment.admin

  tasks:

  # 1. create the database
  # ----------------------

  - name: 1.b Create the glance database
    mysql_db: 
      login_user: "{{ config.mysql_login_user }}"
      login_password: "{{ config.mysql_login_password }}"
      name: glance
      state: present

  - name: 1.c Grant proper access to the glance database
    mysql_user: 
      login_user: "{{ config.mysql_login_user }}"
      login_password: "{{ config.mysql_login_password }}"
      name: glance 
      host: "{{ item }}" 
      password: "{{ config.glance_mysql_password }}" 
      priv: glance.*:ALL
    with_items:
      - "%"
      - localhost

  # 2. Source the admin credentials to gain access to admin-only CLI commands
  # -------------------------------------------------------------------------
  #
  # This is done by environment: config.environment.admin

  # 3. create the service credentials
  # ---------------------------------

  - name: 3.a.1 Delete the glance user if existent
    shell: openstack user delete glance
    ignore_errors: yes

  - name: 3.a.2 Create the glance user
    shell: "openstack user create --password {{ config.glance_user_password }} glance"

  - name: 3.b Add the admin role to the glance user and service project
    shell: "openstack role add --project service --user glance admin"

  - name: 3.c Create the glance service entity
    shell: "openstack service create --name glance --description 'OpenStack Image service' image"

  # 4. Create the Image service API endpoint
  # ----------------------------------------

  - name: 4. Create the Image service API endpoint
    shell: "openstack endpoint create --publicurl {{ config.glance_os_url }} --internalurl {{ config.glance_os_url }} --adminurl {{ config.glance_os_url }} --region RegionOne image"
