---
# http://docs.openstack.org/kilo/install-guide/install/apt/content/glance-install.html
- name:  "Install and configure the Image service components"
  hosts: controller
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:

  - name: 1. Install the packages
    apt: pkg={{item}} state=installed
    with_items:
    - glance 
    - python-glanceclient


   # 2. Edit the /etc/glance/glance-api.conf file and complete the following actions
   
   # WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/glance/glance-api.conf
              regexp='\[DEFAULT\]'
              replace="[DEFAULT_WORKAROUND]"
              backup=no

  - name: "2.a In the [database] section, configure database access:"
    ini_file: dest=/etc/glance/glance-api.conf
              section=database
              option=connection
              value=mysql://glance:{{ config.glance_mysql_password }}@{{ config.controller_node_hostname }}/glance
              backup=no

  - name: "2.b.1 Comment out or remove any other options in the [keystone_authtoken] section"
    ini_file: dest=/etc/glance/glance-api.conf
              section=keystone_authtoken
              state=absent

  - name: "2.b.2 In the [keystone_authtoken] section, configure Identity service access"
    ini_file: dest=/etc/glance/glance-api.conf
              section=keystone_authtoken
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'auth_uri', value: 'http://{{ config.controller_node_hostname }}:5000' }
    - { option: 'auth_url', value: 'http://{{ config.controller_node_hostname }}:35357' }
    - { option: 'auth_plugin', value: 'password' }
    - { option: 'project_domain_id', value: 'default' }
    - { option: 'user_domain_id', value: 'default' }
    - { option: 'project_name', value: 'service' }
    - { option: 'username', value: 'glance' }
    - { option: 'password', value: '{{ config.glance_user_password }}' }

  - name: "2.b.3 In the [paste_deploy] section, configure Identity service access"
    ini_file: dest=/etc/glance/glance-api.conf
              section=paste_deploy
              option=flavor
              value=keystone
              backup=no

  - name: "2.c In the [glance_store] section, configure the local file system store and location of image files"
    ini_file: dest=/etc/glance/glance-api.conf
              section=glance_store
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'default_store', value: 'file' }
    - { option: 'filesystem_store_datadir', value: '/var/lib/glance/images/' }

  - name: "2.d&e In the [DEFAULT] section, configure the noop notification driver to disable notifications because they only pertain to the optional Telemetry service and enable verbose debug output"
    ini_file: dest=/etc/glance/glance-api.conf
              section=DEFAULT_WORKAROUND
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'notification_driver', value: 'noop' }
    - { option: 'verbose', value: 'True' }

  # WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/glance/glance-api.conf
              regexp='\[DEFAULT_WORKAROUND\]'
              replace="[DEFAULT]"
              backup=no

  # 3. Edit the /etc/glance/glance-registry.conf file and complete the following action

  #/etc/glance/glance-registry.conf file:
  # WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/glance/glance-registry.conf
              regexp='\[DEFAULT\]'
              replace="[DEFAULT_WORKAROUND]"
              backup=no

  - name: "3.a In the [database] section, configure database access:"
    ini_file: dest=/etc/glance/glance-registry.conf
              section=database
              option=connection
              value=mysql://glance:{{ config.glance_mysql_password }}@{{ config.controller_node_hostname }}/glance
              backup=no

  - name: "3.b.1 In the [keystone_authtoken] section, configure Identity service access:"
    ini_file: dest=/etc/glance/glance-registry.conf
              section=keystone_authtoken
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'auth_uri', value: 'http://{{ config.controller_node_hostname }}:5000' }
    - { option: 'auth_url', value: 'http://{{ config.controller_node_hostname }}:35357' }
    - { option: 'auth_plugin', value: 'password' }
    - { option: 'project_domain_id', value: 'default' }
    - { option: 'user_domain_id', value: 'default' }
    - { option: 'project_name', value: 'service' }
    - { option: 'username', value: 'glance' }
    - { option: 'password', value: '{{ config.glance_user_password }}' }

  - name: "3.b.2 In the [keystone_authtoken] and >>>>[paste_deploy]<<<< sections, configure Identity service access:"
    ini_file: dest=/etc/glance/glance-registry.conf
              section=paste_deploy
              option=flavor
              value=keystone
              backup=no
  - name: "3.c&d In the [DEFAULT] section, configure the noop notification driver to disable notifications because they only pertain to the optional Telemetry service and enable verbose debug output"
    ini_file: dest=/etc/glance/glance-registry.conf
              section=DEFAULT_WORKAROUND
              option={{ item.option }}
              value={{ item.value }}
              backup=no
    with_items:
    - { option: 'notification_driver', value: 'noop' }
    - { option: 'verbose', value: 'True' }

  # WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING:
  - name: "WORKAROUND FOR BROKEN INI_FILE DEFAULT-SECTION HANDELING, RENAMING [DEFAULT] SECTION"
    replace: dest=/etc/glance/glance-registry.conf
              regexp='\[DEFAULT_WORKAROUND\]'
              replace="[DEFAULT]"
              backup=no

  - name: 4. Populate the Image service database
    shell: 'su -s /bin/sh -c "glance-manage db_sync" glance'
