---
- hosts: all
  tasks:
    - name: Copy install.sh
      copy: src=../../install.sh  dest={{ installation_folder }}/  mode="u=rwx"
    - name: Copy installation folder
      copy: src=../../installation/  dest={{ installation_folder }}/installation  mode="u=rwx"
    - name: Patch by copy
      copy: src=../installation_changed_files/{{ item }}  dest={{ installation_folder }}/installation/{{ item }} backup=yes  mode="u=rwx"
      with_items:
        - install.sh
        - delete_unnecessary_iptables_rules.yml
        - setup_virtual_machines.sh
    - name: Patch by template
      template: src=../installation_changed_files/{{ item }}.j2  dest={{ installation_folder }}/installation/{{ item }} backup=yes  mode="u=rwx"
      with_items:
        - config/installation_configuration.sh
        - config/network/management.xml

