---
- name:  "Install and configure storage node components"
  hosts: object
  roles:
    - config
  sudo: True
  gather_facts: False
  tasks:
  - name: "Install the packages"
    apt: pkg={{item}} state=installed
    with_items:
    - swift
    - swift-account
    - swift-container
    - swift-object

  - name: Get the host part of the IP 
    shell: echo {{ inventory_hostname }}
    register: host_ip

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=account-server.conf.j2 dest=/etc/swift/account-server.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=container-server.conf.j2 dest=/etc/swift/container-server.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=object-server.conf.j2 dest=/etc/swift/object-server.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=container-reconciler.conf.j2 dest=/etc/swift/container-reconciler.conf owner={{ ansible_user_id }}

  - name: "Obtain the accounting, container, object, container-reconciler, and object-expirer service configuration files from the Object Storage source repository:"
    template: src=object-expirer.conf.j2 dest=/etc/swift/object-expirer.conf owner={{ ansible_user_id }}

# Edit the /etc/swift/account-server.conf file and complete the following actions DONE IN FILES

  - name: "Ensure proper ownership of the mount point directory structure:"
    shell: "chown -R swift:swift /srv/node"

  - name: "Create the recon directory and ensure proper ownership of it:"
    shell: "mkdir -p /var/cache/swift; chown -R swift:swift /var/cache/swift"